Timecard/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  root 'employees#index'

  post 'employees/check' => 'employees#check', as: :check
  get 'employees/punch_hours' => 'employees#punch_hours', as: :punch_hours
  get 'employees/view_hours' => 'employees#view_hours', as: :view_hours
  post 'employees/add_hours' => 'employees#add_hours', as: :add_hours
  get 'employees/manager_view_hours' => 'managers#manager_view_hours', as: :manager_view_hours
  post 'employees/manager_view_hours/change_status' => 'managers#change_status', as: :status
  get 'employees/logout' => 'employees#logout', as: :logout
  
  get 'sessions/index' => 'sessions#index', as: :session_index
  get 'sessions/logout' => 'sessions#destroy', as: :session_logout

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  

  resources :sessions, only: [:create, :destroy]
  resources :employees
  

end

Timecard/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :username, :password)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @employee = Employee.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  
  def check
    if Employee.exists?(username: params[:employee][:username], password: params[:employee][:password]) then
       session[:current_user] = params[:employee][:username]
       redirect_to punch_hours_url
    else
      flash[:notice] = "login failed"
      redirect_to employees_path
    end
  end
  
  def logout
    session.delete(:current_user)
    redirect_to employees_path
  end
  
  def punch_hours
    @employee= Employee.find_by username: session[:current_user]
    @hours_worked = Employee.find_by hours_worked: session
  end
  
  def add_hours
    hours_worked = params[:employee_hour][:hours].to_i
    emp_hour = Employee_Hour.create(username: session[:current_user], hours: hours_worked, status: "pending")
    redirect_to view_hours_url
  end
  
  def view_hours
    @employee_hours = Employee_Hour.where(username: session[:current_user])
  end
 
  def index
    @employees = Employee.all
  end
  
  def manager_view_hours
    @employee = Employee.find_by username: session[:current_user]
  end

  def new
    # default: render 'new' template
  end

end

Timecard/app/controllers/managers_controller.rb
class ManagersController < EmployeesController
  def manager_view_hours
    if session[:current_user]
      emp= Employee.find_by username: session[:current_user]
      if emp.isManager == 1
        redirect_to employees_path
      end
    else
      redirect_to employees_path
    end
    @employee_hours = Employee_Hour.all
    @employee =Employee.all
  end
  
  def change_status
    status = params[:status]
    id = params[:object][:id]
    case status
    when '0'
      status ="pending" 
      if (Employee_Hour.where(id: id)[0].status == "approved")
        emp= Employee.find_by username: params[:object][:user]
        hours=  emp.hours_worked - params[:object][:hours].to_i 
        Employee.update(emp.id,:hours_worked => hours)
     end
    when '1'
      status ="approved"
      if (Employee_Hour.where(id: id)[0].status != "approved")
        emp= Employee.find_by username: params[:object][:user]
        hours= params[:object][:hours].to_i + emp.hours_worked
       Employee.update(emp.id,:hours_worked => hours)
     end
    when '2'
      status ="denied"
      if (Employee_Hour.where(id: id)[0].status == "approved")
        emp= Employee.find_by username: params[:object][:user]
        hours=  emp.hours_worked - params[:object][:hours].to_i 
        Employee.update(emp.id,:hours_worked => hours)
     end  
    end
    Employee_Hour.update(id, :status => status)
    redirect_to :back
  end
  def new
      @employee_hours=Employee_Hour.new
  end

end

Timecard/app/views/employees/manager_view_hours.html.haml
-#  This file is app/views/employees/manager_view_hours.html.haml
:css
  form {
    display:block;
  }
  form div label {
    display:inline;
  }
  form div {
    Min-width:100px;
    display:block;
    float:left;
  }
  form input {
    display:block;
    float:left;
  }
  form select {
    display:block;
    float:left;
  }
  h4 {
    display:block;
    Min-width:100px;
    float:left;
  }


%h1 Manager View
%h3 Viewing Employee Hours
%table
  %th
    Employee
  %th
    Hours
  - @employee.each do |ent|
    %tr
      %td 
        =label_tag(:user,ent.username)
      %td 
        =label_tag(:hours,ent.hours_worked)
%h4 Employee
%h4 Hours
%h4 Status
- @employee_hours.each do |emp|
  %form{:controller => "managers", :action => "manager_view_hours/change_status",:method =>"post"}
    %div{:style => "clear:left;"} 
      =label_tag(:user,emp.username) 
    %div 
      =label_tag(:hours,emp.hours)
    %div 
      =emp.status
    =hidden_field :object,:id,:value =>emp.id
    =hidden_field :object,:user,:value =>emp.username
    =hidden_field :object,:hours,:value =>emp.hours
    = select_tag(:status, options_for_select([["pending",0],["approved",1],["denied",2]]))
    =button_to '+'

Timecard/app/views/employees/punch_hours.html.haml
-#  This file is app/views/employees/punch_hours.html.haml

%h1 Punch Hours      
%h2 
    Welcome
    = @employee.first_name
    %h5
        -if @employee.isManager == 0
            = link_to 'Approve/Deny Hours', manager_view_hours_url
        %br
        %br
        =link_to "View Submitted Hours", view_hours_url
    %h3 OR
    
%h3 Please enter hours for this week
= form_tag add_hours_url, :method => :post do
    = label :employee_hour, :hours, 'Hours Worked'
    = text_field :employee_hour, 'hours'
    %br
    = submit_tag 'Click this button'
    %br
   
    

Timecard/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      Team Timecard!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title 
      Team Timecard!
      %div{:class => "homepage"}
        -if session[:current_user]
          =link_to 'Logout', logout_url
      %div{:class => "homepage"}
        -if session[:current_user]
          =link_to 'Homepage', punch_hours_url
        -else
          =link_to 'Homepage', employees_path
      %div{:class => "homepage"}
        -if session[:user_id] 
          =link_to "Logout of Google", session_logout_url
        -else
          =link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in"
      
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield